[package]
name = "gl_rust"
version = "0.1.0"
authors = ["matszczygiel <ms.szczygiel@uw.edu.pl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.22.0-alpha5"
gl = "0.14.0"